#!/usr/bin/env python3
"""metrics.py -- generate packages/pdf/0.1.0/pdf/Metrics.scaly from the AFM
files of the standard fonts (tools/afm/).

    tools/metrics.py [--check]

The table holds, per proportional standard font, the advance width of every
WinAnsiEncoding code 32..255 in thousandths of the font size. Courier is not
in it: every glyph of the four Courier fonts is 600 wide. --check compares the
file in the tree with what would be written and changes nothing.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "packages", "pdf", "0.1.0", "pdf", "Metrics.scaly")

# table order = font id of pdf.Font (family * 4 + bold + 2 * italic)
FONTS = [
    "Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique",
    "Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic",
]

ASCII = (
    "space exclam quotedbl numbersign dollar percent ampersand quotesingle "
    "parenleft parenright asterisk plus comma hyphen period slash zero one two "
    "three four five six seven eight nine colon semicolon less equal greater "
    "question at A B C D E F G H I J K L M N O P Q R S T U V W X Y Z "
    "bracketleft backslash bracketright asciicircum underscore grave a b c d e "
    "f g h i j k l m n o p q r s t u v w x y z braceleft bar braceright "
    "asciitilde"
).split()

HIGH = {
    128: "Euro", 130: "quotesinglbase", 131: "florin", 132: "quotedblbase",
    133: "ellipsis", 134: "dagger", 135: "daggerdbl", 136: "circumflex",
    137: "perthousand", 138: "Scaron", 139: "guilsinglleft", 140: "OE",
    142: "Zcaron", 145: "quoteleft", 146: "quoteright", 147: "quotedblleft",
    148: "quotedblright", 149: "bullet", 150: "endash", 151: "emdash",
    152: "tilde", 153: "trademark", 154: "scaron", 155: "guilsinglright",
    156: "oe", 158: "zcaron", 159: "Ydieresis",
}

LATIN1 = (
    "space exclamdown cent sterling currency yen brokenbar section dieresis "
    "copyright ordfeminine guillemotleft logicalnot hyphen registered macron "
    "degree plusminus twosuperior threesuperior acute mu paragraph "
    "periodcentered cedilla onesuperior ordmasculine guillemotright onequarter "
    "onehalf threequarters questiondown Agrave Aacute Acircumflex Atilde "
    "Adieresis Aring AE Ccedilla Egrave Eacute Ecircumflex Edieresis Igrave "
    "Iacute Icircumflex Idieresis Eth Ntilde Ograve Oacute Ocircumflex Otilde "
    "Odieresis multiply Oslash Ugrave Uacute Ucircumflex Udieresis Yacute "
    "Thorn germandbls agrave aacute acircumflex atilde adieresis aring ae "
    "ccedilla egrave eacute ecircumflex edieresis igrave iacute icircumflex "
    "idieresis eth ntilde ograve oacute ocircumflex otilde odieresis divide "
    "oslash ugrave uacute ucircumflex udieresis yacute thorn ydieresis"
).split()


def glyph_name(code):
    if 32 <= code <= 126:
        return ASCII[code - 32]
    if 160 <= code <= 255:
        return LATIN1[code - 160]
    return HIGH.get(code)


def read_afm(name):
    widths = {}
    with open(os.path.join(HERE, "afm", name + ".afm"), encoding="latin-1") as f:
        for line in f:
            if not line.startswith("C "):
                continue
            wx = glyph = None
            for part in line.split(";"):
                words = part.split()
                if len(words) == 2 and words[0] == "WX":
                    wx = int(words[1])
                elif len(words) == 2 and words[0] == "N":
                    glyph = words[1]
            widths[glyph] = wx
    return widths


def generate():
    assert len(ASCII) == 95 and len(LATIN1) == 96
    lines = [
        "; Metrics -- the advance widths of the proportional standard fonts, per",
        "; WinAnsiEncoding code 32..255, in thousandths of the font size; a code the",
        "; encoding leaves undefined is 0. One row of 224 per font, in the order of",
        "; the font ids (pdf/Font.scaly); the Courier fonts are 600 throughout and",
        "; have no row.",
        ";",
        "; GENERATED by tools/metrics.py from the Adobe Font Metrics files of the",
        "; fourteen standard fonts (tools/afm/). Their notice: Copyright (c) 1985,",
        "; 1987, 1989, 1990, 1997 Adobe Systems Incorporated. All Rights Reserved.",
        "; Do not edit the table by hand.",
        "",
        "define PDF_METRICS_ROW: size_t 224",
        "",
        "define PDF_METRICS: int[] [",
    ]
    rows = []
    for font in FONTS:
        widths = read_afm(font)
        row = []
        for code in range(32, 256):
            name = glyph_name(code)
            if name is None:
                row.append(0)
            else:
                row.append(widths[name])
        rows.append(row)
    for n, row in enumerate(rows):
        lines.append("    ; " + FONTS[n])
        for at in range(0, 224, 16):
            text = ", ".join(str(w) for w in row[at:at + 16])
            last = n == len(rows) - 1 and at + 16 >= 224
            lines.append("    " + text + ("]" if last else ","))
    lines.append("")
    # Unicode of the codes 128..159, which are not Latin-1 (0 = undefined)
    high = []
    for code in range(128, 160):
        try:
            high.append(ord(bytes([code]).decode("cp1252")))
        except UnicodeDecodeError:
            high.append(0)
    lines.append("; the characters at the codes 128..159 (0: the code is undefined)")
    lines.append("define PDF_WINANSI_HIGH: int[] [" + ", ".join("0x%04X" % u for u in high) + "]")
    lines.append("")
    return "\n".join(lines)


def main():
    text = generate()
    if "--check" in sys.argv[1:]:
        with open(OUT, encoding="utf-8") as f:
            if f.read() != text:
                print("metrics: " + OUT + " is not what tools/metrics.py writes")
                return 1
        print("metrics: OK")
        return 0
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
